config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end

  namespace :admin do
    resources :admin_users
    resources :posts
    resources :users
    resources :employees

    root to: "posts#index"
  end
    
  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  root to: "static#homepage"
end

app/views/shared/_admin_dropdown.html.erb
<%= link_to "Admin Dashboard", admin_root_path, class: "dropdown-item" %>
<div class="divider"></div>

app/views/shared/_audit_log.html.erb
<li class="nav-item <%= active?(audit_logs_path) %>">
	<%= link_to "Audit Logs", audit_logs_path, class: "nav-link" %>
</li>

app/views/shared/_employee_nav_items.html.erb
<li class="nav-item <%= active?(posts_path) %>">
  <%= link_to "Time Entries", posts_path, class: "nav-link" %>
</li>

<li class="nav-item <%= active?(posts_path) %>">
  <%= link_to "Request OT", new_post_path, id: "new_post_from_nav", class: "nav-link" %>
</li>

app/views/shared/_nav.html.erb
<div class="logo container">
  <h1>Time Tracker</h1>
</div>

<% if current_user %>
<div class="container">
  <nav class="custom-nav navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= active?(root_path) %>">
          <%= link_to root_path, class: "nav-link" do %>
          <i class="fas fa-home"></i>
          <% end %>
        </li>

        <%= render 'shared/employee_nav_items' if employee? %>

        <%= render 'shared/audit_log' if admin? %>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Options
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= render 'shared/admin_dropdown' if admin? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>

    </div>
  </nav>
</div>
<% end %>

app/views/shared/_notice.html.erb
<% if notice %>
	<div id="notice_wrapper">
		<p class="notice"><%= notice %></p>
	</div>
<% elsif alert %>
	<div id="notice_wrapper">
		<p class="alert"><%= alert %></p>
	</div>
<% end %>